In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('pokemon_data.txt',delimiter='\t')

In [5]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
df.describe() #arroja estadisticas

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [6]:
df.sort_values('Name',ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [7]:
#haciendo cambios a los datos

In [8]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [9]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

In [10]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [11]:
#Para filtrar datos:

In [12]:
df.loc[df['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False,313
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False,405
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False,530
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531

In [15]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False,630
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False,495
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False,590
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False,590
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False,600
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False,590
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False,640
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False,615
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True,780
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False,525
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False,610
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False,610
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False,600
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,600
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False,700
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False,630
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False,635
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False,618
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False,480
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False,480
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False,630
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False,510
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False,575
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False,560
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False,590
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False,555
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False,565
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False,580
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False,700
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False,700
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True,700
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True,700
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True,780
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False,580
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False,700
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False,618
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False,545
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700

In [16]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [20]:
df.loc[df['Total'] > 500, ['Generation', 'Legendary']] = 'TEST VALUE' #PARA CONDICIONALES

In [19]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,TEST VALUE,TEST VALUE,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,TEST VALUE,TEST VALUE,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,TEST VALUE,TEST VALUE,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,TEST VALUE,TEST VALUE,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,TEST VALUE,TEST VALUE,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,TEST VALUE,TEST VALUE,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,TEST VALUE,TEST VALUE,600

In [21]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation   Legendary  Total
0         65       65     45           1       False    318
1         80       80     60           1       False    405
2        100      100     80  TEST VALUE  TEST VALUE    525
3        122      120     80  TEST VALUE  TEST VALUE    625
4         60       50     65           1       False    309
..       ...      ...    ...         ...         ...    ...
795      100      150     50  TEST VALUE  TEST VALUE    600
796      160      110    110  TEST VALUE  TEST VALUE    700
797      150      130     70  TEST VALUE  TEST VALUE    600
798      170      130     80  TEST VALUE  TEST VALUE    680
799      130       90     70  TEST VALUE  TEST VALUE    600

[800 rows x 13 columns]